src/Entity/User.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email", message="Adresse email déjà utilisée.")
 */
class User
    implements UserInterface
{

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email
     */
    protected $email;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Adhesion", mappedBy="user")
     */
    private $adhesions;

    /**
     * @ORM\Column(type="boolean", options={"default":true})
     */
    private $isActive = true;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $longitude;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $passwordRequestedAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    public function __construct()
    {
        $this->adhesions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail( string $email ): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique( $roles );
    }

    public function setRoles( array $roles ): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword( string $password ): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom( string $prenom ): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone( ?string $telephone ): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse( string $adresse ): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille( string $ville ): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal( string $code_postal ): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getDateCreation(): ?DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation( DateTimeInterface $date_creation ): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection|Adhesion[]
     */
    public function getAdhesions(): Collection
    {
        return $this->adhesions;
    }

    public function addAdhesion( Adhesion $adhesion ): self
    {
        if( ! $this->adhesions->contains( $adhesion ) ) {
            $this->adhesions[] = $adhesion;
            $adhesion->setUser( $this );
        }

        return $this;
    }

    public function removeAdhesion( Adhesion $adhesion ): self
    {
        if( $this->adhesions->contains( $adhesion ) ) {
            $this->adhesions->removeElement( $adhesion );
            // set the owning side to null (unless already changed)
            if( $adhesion->getUser() === $this ) {
                $adhesion->setUser( null );
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNom();
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom( string $nom ): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive( bool $isActive ): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude( ?float $longitude ): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude( ?float $latitude ): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription( ?string $description ): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPasswordRequestedAt(): ?DateTimeInterface
    {
        return $this->passwordRequestedAt;
    }

    public function setPasswordRequestedAt( ?DateTimeInterface $passwordRequestedAt ): self
    {
        $this->passwordRequestedAt = $passwordRequestedAt;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken( ?string $token ): self
    {
        $this->token = $token;

        return $this;
    }

}

templates/pages/annuairePartial.html.twig
{% set card_construct %}
    {% if response is defined %}
            {% for result in response %}
                <div class="card p-0 mb-2" id="{{ result.0.id }}">
                    <div class="card-header">

                        <p>{{ result.denomination }}
                            {% if result.distance is defined %}
                                <span class="pull-right text-primary">{{ result.distance | slice(0, 4) }} Km</span>
                            {% endif %}
                        </p>
                        <h6 class="card-subtitle mb-2 text-muted">
                            {% if result.categories is defined %}
                                {% for res in result.categories %}
                                    {{ res }}
                                {% endfor %}
                            {% endif %}
                        </h6>
                    </div>
                    <div class="card-body text-dark">
                        {% if result.0.adresse | length > 0 or result.0.ville | length > 0 %}
                            <p class="card-text">
                                <i class="fa fa-map-marker" aria-hidden="true"></i> {{ result.0.adresse }}, {{ result.0.codePostal }} {{ result.0.ville }}
                            </p>
                        {% endif %}
                        {% if result.0.telephone | length > 0 %}
                            {% set splitArray = result.0.telephone | split('', 2) %}
                            {% set formattedPhone = splitArray|join(' ') %}
                            <p class="card-text">
                                <i class="fa fa-phone" aria-hidden="true"></i> {{ formattedPhone }}
                            </p>
                        {% endif %}
                        {% if result.0.description | length > 0 %}
                            <p class="card-text mb-0">
                                <i class="fa fa-id-card" aria-hidden="true"></i> {{ result.0.description | easyadmin_truncate(100) | raw }}
                            </p>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
    {% endif %}
{% endset %}

{% set response = response|merge({'card': card_construct}) %}

{{ response|json_encode(constant('JSON_PRETTY_PRINT'))|raw }}

templates/pages/blogArticle.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.title }} - Le blog - {{ parent() }}{% endblock %}

{% block body %}
    <a href="{{ path('blog') }}" class="btn blanc bg-principale mb-5">&laquo; Retour au blog</a>
    <article class="mb-5">
        <h2 class="principale">{{ article.title }}</h2>
        <p class="text-muted mb-3">
            <span class="font-weight-bold">Publié le</span> {{ article.createdAt | date('d/m/Y') }}
            <span class="font-weight-bold">à</span> {{ article.createdAt | date('H:i') }}
        </p>
        <div class="content">
            {% if 'http' in article.image %}
                <img src="{{ article.image }}" alt="{{ article.imageDescription }}" />
            {% else %}
                <img src="/uploads/images/articles/{{ article.image }}" alt="{{ article.imageDescription }}" />
            {% endif %}
            <div class="mt-5">{{ article.content | raw }}</div>
        </div>
    </article>
{% endblock %}

templates/pages/cgu.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conditions Générales d'Utilisation - {{ parent() }}{% endblock %}

{% block body %}
    <h1 class="principale">Conditions Générales d'Utilisation</h1>

    {{ informationsLegales.cgu | raw }}
{% endblock %}

templates/pages/cgv.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conditions Générales de Vente - {{ parent() }}{% endblock %}

{% block body %}
    <h1 class="principale">Conditions Générales de Vente</h1>

    {{ informationsLegales.cgv | raw }}
{% endblock %}

templates/pages/compteRenduAG.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Compte-rendu de la dernière Assemblée Générale de l'association - {{ parent() }}
{% endblock %}

{% block body %}
    <h1 class="principale">Compte-rendu de la dernière Assemblée Générale de l'association</h1>

    {{ informationsAssociation.compteRenduAG | raw }}
{% endblock %}

templates/pages/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Nous contacter - {{ parent() }}
{% endblock %}

{% block body %}
    {#Titre Principal#}
    <h1 class="principale mb-5">
        Nous sommes là pour vous répondre
    </h1>
    {# ****************************************************************** #}

    {# Contenu de la vue #}
    <div class="row">
        <div class="col-md-8 mb-5">
            <h4>
                Nous écrire
            </h4>
            {# Message de succès de l'envoi du formulaire #}
            {% for message in app.flashes('success') %}
                <div class="text-center alert alert-success">
                    <i class="fa fa-check"></i> <span>{{ message }}</span>
                </div>
            {% endfor %}

            {# ****************************************************************** #}
            {# Message d'échec de l'envoi du formulaire #}
            {% if not form.vars.valid %}
                <div class="text-center alert alert-danger">
                    <i class="fa fa-times"></i>
                    <span>Les champs doivent contenir au moins 2 caractères et le message 10 caractères.</span>
                </div>
            {% endif %}
            {# ****************************************************************** #}

            {# Formulaire de contact #}
            <div class="border-principale py-3 px-3">
                <form action="{{ path('contact') }}" method="post">
                    {{ form_start(form, {'attr': {'id': 'contact-form'}}) }}
                    <div class="row">
                        <div class="form-group col-6">
                            {{ form_widget(form.firstName, {'attr' : {'placeholder': "Prénom", "name":"firstName", "class": "form-control"}}) }}
                        </div>
                        <div class="form-group col-6">
                            {{ form_widget(form.lastName, {'attr' : {'placeholder': "Nom", "name":"lastName", "class": "form-control"}}) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_widget(form.email, {'attr' : {'placeholder': "Adresse email (ex: pierre@bmail.com)", "name":"email", "class": "form-control"}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_widget(form.object, {'attr' : {'placeholder': "Objet", "name":"object", "class": "form-control"}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_widget(form.message, {'attr' : {'placeholder': "Votre message", 'class': 'message', "name":"message", "class": "form-control", 'rows': '10'}}) }}
                    </div>
                    <div class="form-group text-right">
                        <button type="submit" class="btn blanc bg-principale">Envoyer</button>
                        <input id="recaptchaToken" name="recaptchaToken" type="hidden" />
                    </div>
                    {{ form_end(form) }}
                </form>
            </div>
            {# ****************************************************************** #}
        </div>
        {# Informations de contact #}
        <div class="col-md-4">
            <h4 class="title">
                Nous contacter autrement
            </h4>
            <div class="card border-principale text-center mb-3" style="max-width: 20rem;">
                <div class="card-body">
                    <h5 class="card-title">Email</h5>
                    <p class="card-text">{{ infosContact.email }}</p>
                </div>
            </div>
            {% if infosContact.telephone %}
                <div class="card border-principale text-center mb-3" style="max-width: 20rem;">
                    <div class="card-body">
                        <h5 class="card-title">Téléphone</h5>
                        <p class="card-text">{{ infosContact.telephone }}</p>
                    </div>
                </div>
            {% endif %}
            {% if infosContact.adresse and infosContact.codePostal and infosContact.ville %}
                <div class="card border-principale text-center mb-3" style="max-width: 20rem;">
                    <div class="card-body">
                        <h5 class="card-title">Adresse</h5>
                        <p class="card-text">{{ infosContact.adresse }}, {{ infosContact.codePostal }} {{ infosContact.ville }}</p>
                    </div>
                </div>
            {% endif %}
            <div class="card border-principale text-center mb-3" style="max-width: 20rem;">
                <div class="card-body">
                    <h5 class="card-title">Réseaux sociaux</h5>
                    <p class="card-text">
                        {% if infosContact.facebook %}
                    <div>
                        <a class="card-link principale" href='{{ infosContact.facebook }}' target="_blank">
                            <i class="fa fa-facebook-square facebook-icon-contact"></i>&nbsp;
                            &nbsp;Facebook</a>
                    </div>
                    {% endif %}
                    {% if infosContact.twitter %}
                        <div>
                            <a class="card-link principale" href='{{ infosContact.twitter }}' target="_blank">
                                <i class="fa fa-twitter-square facebook-icon-contact"></i>&nbsp;
                                &nbsp;Twitter</a>
                        </div>
                    {% endif %}
                    {% if infosContact.instagram %}
                        <div>
                            <a class="card-link principale" href='{{ infosContact.instagram }}' target="_blank">
                                <i class="fa fa-instagram facebook-icon-contact"></i>&nbsp;
                                &nbsp;Instagram</a>
                        </div>
                    {% endif %}
                    </p>
                </div>
            </div>
        </div>
        {# ****************************************************************** #}
    </div>
    {# ****************************************************************** #}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="https://www.google.com/recaptcha/api.js?render={{ siteKey }}"></script>
    <script type="text/javascript">
        grecaptcha.ready(function () {
            grecaptcha.execute("{{ siteKey }}", {
                action: 'homepage'
            }).then(function (token) {
                document.getElementById('recaptchaToken').value = token;
            });
        });
    </script>
{% endblock %}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% for message in app.flashes('danger') %}
        <div class="text-center alert alert-dismissible alert-danger">
            <i class="fa fa-times"></i> <span>{{ message }}</span>
        </div>
    {% endfor %}

    <section class="presentation mb-5">
        <h2 class="principale mb-4">{{ informations.titrepresentation | raw }}</h2>
        {{ informations.presentation | raw }}
    </section>

    <section class="evenements">
        <h2 class="principale mt-5">Événements à venir</h2>
        <div class="mb-3">
            {% for event in evenements|reverse %}
                <div class="py-4">
                    <div class="row">
                        <div class="overflow-hidden col-md-4 mb-3">
                            <img src="{{ event.image }}" alt="{{ event.imageDescription }}" class="images">
                        </div>
                        <div class="col-md-8">
                            <h5 class="mt-2">
                                {{ event.title }}
                            </h5>
                            <p class="text-muted">
                                <strong>Date : </strong>{{ event.date | date('d/m/Y') }} &nbsp;&nbsp; |
                                &nbsp;&nbsp;
                                <strong>Heure : </strong>{{ event.date | date('H:i') }} &nbsp;&nbsp; | &nbsp;&nbsp;
                                <strong>Lieu : </strong>{{ event.lieu }}</small></p>
                            <p>{{ event.description |easyadmin_truncate(100) |raw }}</p>
                            <a href="{{ event.lienEvent }}" class="btn btn-sm blanc bg-principale" target="_blank">voir l'événement</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>

    <section class="evenements">
        <h2 class="principale">Derniers articles</h2>
        <div class="mb-3">
            {% for article in articles|reverse if article.isActive == true %}
                <div class="py-4">
                    <div class="row">
                        {% if 'http' in article.image %}
                            <div class="overflow-hidden col-md-4 mb-3">
                                <img src="{{ article.image }}" alt="{{ article.imageDescription }}" class="images">
                            </div>
                        {% else %}
                            <div class="overflow-hidden col-md-4 mb-3">
                                <img src="/uploads/images/articles/{{ article.image }}" alt="{{ article.imageDescription }}"
                                        class="images">
                            </div>
                        {% endif %}
                        <div class="col-md-8">
                            <h5 class="mt-2">
                                {{ article.title }}
                            </h5>
                            <p class="text-muted"><small>Publié le {{ article.createdAt | date('d/m/Y') }} &nbsp; à
                                    {{ article.createdAt | date('H:i') }}</small></p>
                            <p>{{ article.content |easyadmin_truncate(100) |raw }}</p>
                            <a href="{{ path('blogArticle', {'id': article.id}) }}" class="btn btn-sm blanc bg-principale">lire la suite</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/pages/mentionsLegales.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mentions légales - {{ parent() }}{% endblock %}

{% block body %}
    <h1 class="principale">Mentions légales</h1>

    {{ informationsLegales.mentionsLegales | raw }}
{% endblock %}

templates/pages/modalPartial.html.twig
<div class="modal fade" id="modal_presta" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="presta_denomination"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p><span class="font-weight-bold"><span id="pref"></span></span><span id="categorie"></span></p>
                <p><span class="font-weight-bold">Description :</span> <span id="description"></span></p>
                <p><span class="font-weight-bold">Site internet :</span> <span id="site"></span></p>
                <p><span class="font-weight-bold">Adresse :</span> <span id="adresse"></span></p>
            </div>
        </div>
    </div>
</div>

templates/pages/procurer.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Où s'en procurer - {{ parent() }}
{% endblock %}

{% block body %}
    <h1 class="principale mb-4">Où s'en procurer</h1>
    <div class="row py-3 px-3">
        <div class="input-group mb-3">
            <input class="form-control " type="text" placeholder="Rechercher" id="search" name="search" />
            <select class="custom-select" id="sel2">
                <option>Toutes les distances</option>
                <option>15km</option>
                <option>30km</option>
                <option>50km</option>
                <option>80km</option>
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mt-3">
            <div id="map"></div>
            <div class="mt-3"><a class="btn bg-principale blanc" href={{ path('pdf.comptoirs') }}>Annuaire comptoir</a></div>
        </div>
        <div class="col mt-3">
            <div id="annuaire" class="prestataire"></div>
        </div>
    </div>
    {% include 'pages/modalPartial.html.twig' %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin="">
    </script>
    <script type="text/javascript" src="/js/geolocalisation.js"></script>
    <script type="text/javascript" src="/js/set_map.js"></script>
    <script type="text/javascript" src="/js/ajax-annuaire.js"></script>
    <script type="text/javascript" src="/js/event.js"></script>
    <script type="text/javascript">
        setEvent('{{ status }}');
    </script>
{% endblock %}

templates/pages/reglementInterieur.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Règlement intérieur de l'association - {{ parent() }}
{% endblock %}

{% block body %}
    <h1 class="principale">Règlement intérieur de l'association</h1>

    {{ informationsAssociation.reglementInterieur | raw }}
{% endblock %}

templates/pages/statuts.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Statuts de l'association - {{ parent() }}
{% endblock %}

{% block body %}
    <h1 class="principale">Statuts de l'association</h1>

    {{ informationsAssociation.statuts | raw }}
{% endblock %}

templates/pages/utiliser.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Où les utiliser - {{ parent() }}
{% endblock %}

{% block body %}

    <h1 class="principale mb-4">Où utiliser les pelous</h1>
    <div class="row py-3 px-3">
        <div class="input-group mb-3">
            <input class="form-control" type="text" placeholder="Rechercher" id="search" name="search" />
            <select class="custom-select" id="sel1">
                <option>Tous les services</option>
                {% for categorie in categories %}
                    <option>{{ categorie }}</option>
                {% endfor %}
            </select> <select class="custom-select" id="sel2">
                <option>Toutes les distances</option>
                <option>15km</option>
                <option>30km</option>
                <option>50km</option>
                <option>80km</option>
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mt-3">
            <div id="map"></div>
            <div class="mt-3"><a class="btn bg-principale blanc" href={{ path('pdf.prestataires') }}>Annuaire prestataire</a></div>
        </div>
        <div class="col mt-3">
            <div id="annuaire" class="prestataire"></div>
        </div>
    </div>
    {% include 'pages/modalPartial.html.twig' %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin="">
    </script>
    <script type="text/javascript" src="/js/geolocalisation.js"></script>
    <script type="text/javascript" src="/js/set_map.js"></script>
    <script type="text/javascript" src="/js/ajax-annuaire.js"></script>
    <script type="text/javascript" src="/js/event.js"></script>
    <script type="text/javascript">
        setEvent('{{ status }}');
    </script>
{% endblock %}