src/Entity/Comptoir.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ComptoirRepository")
 */
class Comptoir
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $site_internet;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $siret;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $denomination;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $solde;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSiteInternet(): ?string
    {
        return $this->site_internet;
    }

    public function setSiteInternet( ?string $site_internet ): self
    {
        $this->site_internet = $site_internet;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret( ?string $siret ): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getDenomination(): ?string
    {
        return $this->denomination;
    }

    public function setDenomination( string $denomination ): self
    {
        $this->denomination = $denomination;

        return $this;
    }

    public function getNom()
    {
        return $this->getUser()->getNom();
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser( User $user ): self
    {
        $this->user = $user;

        return $this;
    }

    public function setNom( string $nom )
    {
        return $this->getUser()->setNom( $nom );
    }

    public function getDescription()
    {
        return $this->getUser()->getDescription();
    }

    public function setDescription( $description )
    {
        return $this->getUser()->setDescription( $description );
    }

    public function getPrenom()
    {
        return $this->getUser()->getPrenom();
    }

    public function setPrenom( string $prenom )
    {
        return $this->getUser()->setPrenom( $prenom );
    }

    public function getIsActive()
    {
        return $this->getUser()->getIsActive();
    }

    public function setIsActive( bool $isActive )
    {
        return $this->getUser()->setIsActive( $isActive );
    }

    public function getTelephone()
    {
        return $this->getUser()->getTelephone();
    }

    public function setTelephone( string $telephone )
    {
        return $this->getUser()->setTelephone( $telephone );
    }

    public function getEmail()
    {
        return $this->getUser()->getEmail();
    }

    public function setEmail( string $email )
    {
        return $this->getUser()->setEmail( $email );
    }

    public function getAdresse()
    {
        return $this->getUser()->getAdresse();
    }

    public function setAdresse( string $adresse )
    {
        return $this->getUser()->setAdresse( $adresse );
    }

    public function getVille()
    {
        return $this->getUser()->getVille();
    }

    public function setVille( string $ville )
    {
        return $this->getUser()->setVille( $ville );
    }

    public function getCodePostal()
    {
        return $this->getUser()->getCodePostal();
    }

    public function setCodePostal( string $codePostal )
    {
        return $this->getUser()->setCodePostal( $codePostal );
    }

    public function getSolde(): ?float
    {
        return $this->solde;
    }

    public function setSolde( ?float $solde ): self
    {
        $this->solde = $solde;

        return $this;
    }

    public function __toString()
    {
        return $this->denomination;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email", message="Adresse email déjà utilisée.")
 */
class User
    implements UserInterface
{

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email
     */
    protected $email;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Adhesion", mappedBy="user")
     */
    private $adhesions;

    /**
     * @ORM\Column(type="boolean", options={"default":true})
     */
    private $isActive = true;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $longitude;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $passwordRequestedAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    public function __construct()
    {
        $this->adhesions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail( string $email ): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique( $roles );
    }

    public function setRoles( array $roles ): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword( string $password ): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom( string $prenom ): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone( ?string $telephone ): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse( string $adresse ): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille( string $ville ): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal( string $code_postal ): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getDateCreation(): ?DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation( DateTimeInterface $date_creation ): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection|Adhesion[]
     */
    public function getAdhesions(): Collection
    {
        return $this->adhesions;
    }

    public function addAdhesion( Adhesion $adhesion ): self
    {
        if( ! $this->adhesions->contains( $adhesion ) ) {
            $this->adhesions[] = $adhesion;
            $adhesion->setUser( $this );
        }

        return $this;
    }

    public function removeAdhesion( Adhesion $adhesion ): self
    {
        if( $this->adhesions->contains( $adhesion ) ) {
            $this->adhesions->removeElement( $adhesion );
            // set the owning side to null (unless already changed)
            if( $adhesion->getUser() === $this ) {
                $adhesion->setUser( null );
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNom();
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom( string $nom ): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive( bool $isActive ): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude( ?float $longitude ): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude( ?float $latitude ): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription( ?string $description ): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPasswordRequestedAt(): ?DateTimeInterface
    {
        return $this->passwordRequestedAt;
    }

    public function setPasswordRequestedAt( ?DateTimeInterface $passwordRequestedAt ): self
    {
        $this->passwordRequestedAt = $passwordRequestedAt;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken( ?string $token ): self
    {
        $this->token = $token;

        return $this;
    }

}

src/Controller/PdfController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\UserRepository;
use App\Repository\CategorieRepository;
use Dompdf\Dompdf;
use Dompdf\Options;

class PdfController
    extends AbstractController
{

    /**
     * @Route("/formulaire_adhesion", name="pdf.adhesion")
     */
    public function pdfAdhesion()
    {
        $pdfOptions = new Options();
        $pdfOptions->set( 'defaultFont', 'Arial' );
        $dompdf = new Dompdf( $pdfOptions );

        $html = $this->renderView( 'pdf/adhesionPdf.html.twig' );

        $dompdf->loadHtml( $html );
        $dompdf->setPaper( 'A4', 'portrait' );
        $dompdf->render();

        $dompdf->stream( "adhesion-lou-pelou.pdf",
            [
                "Attachment" => true,
            ] );
    }

    /**
     * @Route("profil/imprimer", name="profil.pdf")
     */
    public function pdfAdherent()
    {
        $pdfOptions = new Options();
        $pdfOptions->set( 'defaultFont', 'Arial' );
        $dompdf = new Dompdf( $pdfOptions );

        $user = $this->getUser();

        $html = $this->renderView( 'pdf/profilPdf.html.twig',
            [
                'user' => $user,

            ] );

        $dompdf->loadHtml( $html );
        $dompdf->setPaper( 'A4', 'portrait' );
        $dompdf->render();

        $dompdf->stream( "adherent.pdf",
            [
                "Attachment" => true,
            ] );
    }

    /**
     * @Route("/annuaire_comptoirs", name="pdf.comptoirs")
     */
    public function pdfComptoirs( UserRepository $userRepository )
    {

        $pdfOptions = new Options();
        $pdfOptions->set( 'defaultFont', 'Arial' );

        $dompdf = new Dompdf( $pdfOptions );

        $resComptoir =
            $userRepository->findByParams( array( 'status' => 'comptoir', 'filter' => 'Tous les services' ) );

        $html = $this->renderView( 'pdf/pdfComptoirs.html.twig',
            [
                'comptoir' => $resComptoir,
            ] );

        $dompdf->loadHtml( $html );

        $dompdf->render();

        $dompdf->stream( "annuaire-comptoirs.pdf",
            [
                "Attachment" => true,
            ] );
    }

    /**
     * @Route("/annuaire_prestataires", name="pdf.prestataires")
     */
    public function pdfPrestataires( CategorieRepository $categorieRepo )
    {

        $pdfOptions = new Options();
        $pdfOptions->set( 'defaultFont', 'Arial' );

        $dompdf = new Dompdf( $pdfOptions );

        $categories = $categorieRepo->findAll();

        $prestaCate = array();

        foreach( $categories as $categorie ) {
            $nom                = $categorie->getNom();
            $prestataireCate    = $categorie->getPrestataires()->getValues();
            $prestaCate[ $nom ] = $prestataireCate;
        }

        $html = $this->renderView( 'pdf/pdfPrestataires.html.twig',
            [
                'prestaCate' => $prestaCate,
            ] );

        $dompdf->loadHtml( $html );

        $dompdf->render();

        $dompdf->stream( "annuaire-prestataires.pdf",
            [
                "Attachment" => true,
            ] );
    }
}

templates/pdf/adhesionPdf.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
    </head>

    <body>
        <h1 style="color: #BD2F3A">Le Chemin Limousin<br /><span style="font-size: 80%; color: #000000;"><em>Formulaire d'adhésion</em></span>
        </h1>

        <hr style="margin: 20px 0; border-color: #BD2F3A;" />

        <p style="padding: 10px 20px; color: #565656;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas rutrum molestie lacus vel scelerisque. Aenean egestas, quam in pulvinar mollis, eros libero accumsan ligula, fringilla pulvinar nibh turpis vel nibh. Maecenas dictum nisl nibh, at rhoncus est commodo vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt felis ac pellentesque convallis. Ut viverra quam vel est ultricies, vitae aliquet metus ultrices. In hac habitasse platea dictumst. Aliquam suscipit placerat mattis. Pellentesque sollicitudin nisi ex, quis porta elit tempus et. Cras nec mauris neque. Integer mi ante, lobortis sed convallis eu, malesuada ac eros.</p>

        <hr style="margin: 20px 0 40px 0; border-color: #BD2F3A;" />

        <form>
            <div style="margin: 10px 0;">
                <label style="display: inline-block; width: 25%; font-weight: bold; color: #BD2F3A;">Votre prénom :</label>
                <input type="text" style="width: 73%; height: 26px; vertical-align: middle;" />
            </div>
            <div style="margin: 10px 0;">
                <label style="display: inline-block; width: 25%; font-weight: bold; color: #BD2F3A;">Votre nom :</label>
                <input type="text" style="width: 73%; height: 26px; vertical-align: middle;" />
            </div>
            <div style="margin: 10px 0;">
                <label style="display: inline-block; width: 25%; font-weight: bold; color: #BD2F3A;">Votre téléphone :</label>
                <input type="text" style="width: 73%; height: 26px; vertical-align: middle;" />
            </div>
            <div style="margin: 10px 0;">
                <label style="display: inline-block; width: 25%; font-weight: bold; color: #BD2F3A;">Votre adresse e-mail :</label>
                <input type="text" style="width: 73%; height: 26px; vertical-align: middle;" />
            </div>

            <hr style="margin: 40px 0; border-color: #BD2F3A;" />

            <div style="margin: 10px 0;">
                <label style="display: inline-block; width: 25%; font-weight: bold; color: #BD2F3A;">Votre adresse :</label>
                <input type="text" style="width: 73%; height: 26px; vertical-align: middle;" />
            </div>
            <div style="margin: 10px 0;">
                <label style="display: inline-block; width: 25%; font-weight: bold; color: #BD2F3A;">Votre code postal :</label>
                <input type="text" style="width: 73%; height: 26px; vertical-align: middle;" />
            </div>
            <div style="margin: 10px 0;">
                <label style="display: inline-block; width: 25%; font-weight: bold; color: #BD2F3A;">Votre ville :</label>
                <input type="text" style="width: 73%; height: 26px; vertical-align: middle;" />
            </div>
        </form>

        <hr style="margin: 40px 0 20px 0; border-color: #BD2F3A;" />

        <p style="padding: 10px 20px; color: #565656;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas rutrum molestie lacus vel scelerisque. Aenean egestas, quam in pulvinar mollis, eros libero accumsan ligula, fringilla pulvinar nibh turpis vel nibh.</p>
    </body>
</html>

templates/pdf/constructorComptoir.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Annuaire comptoir</title>
    </head>

    <body>
        <img src="images/pdf/comptoir.jpg" style="width: 100%">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Nom</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Téléphone</th>
                    <th scope="col">Email</th>
                    <th scope="col">Site</th>
                </tr>
            </thead>
            <tbody>
                {% for result in comptoir %}
                    <tr>
                        <td>{{ result.denomination }}</td>
                        <td>{{ result.0.adresse }} {{ result.0.ville }}</td>
                        <td>{{ result.0.telephone }}</td>
                        <td>{{ result.0.email }}</td>
                        <td>{{ result.site_internet }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </body>

templates/pdf/pdfComptoirs.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Annuaire comptoir</title>
    </head>

    <body>
        <img src="images/pdf/comptoir.jpg" style="width: 100%">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Nom</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Téléphone</th>
                    <th scope="col">Email</th>
                    <th scope="col">Site</th>
                </tr>
            </thead>
            <tbody>
                {% for result in comptoir %}
                    <tr>
                        <td>{{ result.denomination }}</td>
                        <td>{{ result.0.adresse }} {{ result.0.ville }}</td>
                        <td>{{ result.0.telephone }}</td>
                        <td>{{ result.0.email }}</td>
                        <td>{{ result.site_internet }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </body>

templates/pdf/pdfPrestataires.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Annuaire prestataire</title>
    </head>

    <body>
        {% for key,value in prestaCate %}
            {% if not value is empty %}
                <div class="text-center" style="width: 100%; background-color: #960A00; margin: 20px; box-sizing:border-box; padding: 10px; color: #FFE803">
                    <h1>{{ key }}</h1>
                </div>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Nom</th>
                            <th scope="col">Adresse</th>
                            <th scope="col">Téléphone</th>
                            <th scope="col">Email</th>
                            <th scope="col">Site</th>
                        </tr>
                    </thead>
                    {% for presta in value %}
                        <tbody>
                            <tr>
                                <td>{{ presta.denomination }}</td>
                                <td>{{ presta.user.adresse }} <br> {{ presta.user.codePostal }}
                                    <br> {{ presta.user.ville }}</td>
                                <td>{{ presta.user.telephone }}</td>
                                <td>{{ presta.user.email }}</td>
                                <td>{{ presta.siteInternet }}</td>
                            </tr>
                        </tbody>
                    {% endfor %}
                </table>
            {% endif %}
        {% endfor %}
    </body>
    <script src="https://kit.fontawesome.com/84a428c253.js"></script>
</html>

templates/pdf/profilPdf.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
    </head>

    <body>
        <div id="containerProfil">
            <div style="text-align:center; font-family:verdana;" id="blockProfil">
                <h2 id="profilTitle">Mon profil</h2>
                <p>Prénom : {{ user.prenom }}</p>
                <p>Nom : {{ user.nom }}</p>
                <p>Email : {{ user.email }}</p>
                <p>Adresse : {{ user.adresse }}</p>
                <p>Ville : {{ user.ville }}</p>
                <p>Code postal : {{ user.codepostal }}</p>
            </div>
        </div>
    </body>
</html>